-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 11:30:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seid` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `seid` ;

-- -----------------------------------------------------
-- Table `seid`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seid`.`sucursales` (
  `id_sucursal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_sucursal` VARCHAR(45) NOT NULL,
  `direccion_sucursal` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  UNIQUE INDEX `nombre_sucursal_UNIQUE` (`nombre_sucursal` ASC) VISIBLE,
  UNIQUE INDEX `direccion_sucursal_UNIQUE` (`direccion_sucursal` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `seid`.`credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seid`.`credenciales` (
  `id_credencial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nivel_usuario` VARCHAR(70) NOT NULL,
  `nombres_credencial` VARCHAR(55) NOT NULL,
  `apellidos_credencial` VARCHAR(45) NOT NULL,
  `curp_credencial` VARCHAR(55) NOT NULL,
  `telefono_credencial` VARCHAR(18) NOT NULL,
  `correo_inicio` VARCHAR(55) NOT NULL,
  `pass_inicio` VARCHAR(250) NOT NULL,
  `token_verificacion` VARCHAR(25) NOT NULL,
  `id_sucursal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_credencial`),
  UNIQUE INDEX `curp_credencial_UNIQUE` (`curp_credencial` ASC) VISIBLE,
  UNIQUE INDEX `telefono_credencial_UNIQUE` (`telefono_credencial` ASC) VISIBLE,
  UNIQUE INDEX `correo_inicio_UNIQUE` (`correo_inicio` ASC) VISIBLE,
  CONSTRAINT `id_sucursal`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `seid`.`sucursales` (`id_sucursal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `seid`.`qr_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seid`.`qr_codes` (
  `id_qr_codes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_credencial_qr_codes` INT UNSIGNED NOT NULL,
  `file_path` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_qr_codes`),
  UNIQUE INDEX `id_credencial_qr_codes_UNIQUE` (`id_credencial_qr_codes` ASC) VISIBLE,
  CONSTRAINT `id_credencial_qr_codes`
    FOREIGN KEY (`id_credencial_qr_codes`)
    REFERENCES `seid`.`credenciales` (`id_credencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `seid`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seid`.`registros` (
  `id_registros` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_credencial_registros` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_entrada` DATETIME NOT NULL,
  PRIMARY KEY (`id_registros`),
  INDEX `id_credencial_registros_idx` (`id_credencial_registros` ASC) VISIBLE,
  CONSTRAINT `id_credencial_registros`
    FOREIGN KEY (`id_credencial_registros`)
    REFERENCES `seid`.`credenciales` (`id_credencial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
